SELECT * FROM  employees;
--select * FrOM JOBS;
--SELECT * FROM  employees WHERE first_NAME ='Steven';
-- single line command

SELECT FIRST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;
/*
 get first name and salary from employee
 */

 SELECT FIRST_NAME,SALARY FROM  EMPLOYEES;

SELECT  FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT CITY From LOCATIONS;

SELECT COUNTRY_NAME,REGION_ID From COUNTRIES;

SELECT JOB_ID,JOB_TITLE From JOBS;

SELECT STREET_ADDRESS,POSTAL_CODE From LOCATIONS;

SELECT DEPARTMENT_NAME FROM DEPARTMENTS;

SELECT  REGION_NAME From REGIONS;