SELECT * From Employees;
SELECT STREET_ADDRESS, POSTAL_CODE from LOCATIONS;
SELECT DISTINCT STREET_ADDRESS, POSTAL_CODE from LOCATIONS;

SELECT FIRST_NAME FROM EMPLOYEES;
SELECT Distinct FIRST_NAME FROM EMPLOYEES;

select Distinct JOB_ID from EMPLOYEES;

-- unique country from location
SELECT COUNTRY_ID from LOCATIONS;
SELECT Distinct COUNTRY_ID from LOCATIONS;

SELECT Distinct JOB_ID from JOBS;

--Where is condition
